package background;

import com.ftn.sbnz.model.CharSheet;
import com.ftn.sbnz.model.PathInLife;
import com.ftn.sbnz.model.Interest;
import com.ftn.sbnz.model.WayOfLife;
import com.ftn.sbnz.model.BackgroundParams;
import com.ftn.sbnz.model.Background;
import java.util.ArrayList;
import java.util.Arrays
import java.util.List;

dialect  "mvel"

// LONER
rule "wayoflife_loner"
no-loop true
salience 101
    when
        BackgroundParams(wayOfLife==WayOfLife.LONER)
        $interests: ArrayList();
    then
        modify($interests){add(Interest.CITY_DWELLING)};
        modify($interests){add(Interest.NATURE_DWELLING)};
end

rule "interest_city"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.LONER && interest==Interest.CITY_DWELLING)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.VIOLENCE)};
        modify($paths){add(PathInLife.PICKPOCKETING)};
        modify($paths){add(PathInLife.SWINDLING)};
end

rule "CRIMINAL" // pathinlife==violence
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.LONER && interest==Interest.CITY_DWELLING && path==PathInLife.VIOLENCE)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.CRIMINAL)};
end

rule "URCHIN" // pathinlife==pickpocketing
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.LONER && interest==Interest.CITY_DWELLING && path==PathInLife.PICKPOCKETING)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.URCHIN)};
end

rule "CHARLATAN" // pathinlife==swindling
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.LONER && interest==Interest.CITY_DWELLING && path==PathInLife.SWINDLING)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.CHARLATAN)};
end

rule "HERMIT" // interest==nature, path==null
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.LONER && interest==Interest.NATURE_DWELLING)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.HERMIT)};
end


// ORGANIZATION MEMBER
rule "wayoflife_org_member"
no-loop true
salience 101
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER)
        $interests: ArrayList();
    then
        modify($interests){add(Interest.ARTISTIC)};
        modify($interests){add(Interest.RELIGIOUS)};
        modify($interests){add(Interest.VIOLENT)};
end

rule "interest_artistic"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.ARTISTIC)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.PERFORMER)};
        modify($paths){add(PathInLife.CRAFTSMAN)};
end

rule "ENTERTAINER" // path==performer
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.ARTISTIC && path==PathInLife.PERFORMER)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.ENTERTAINER)};
end

rule "GUILD_ARTISAN" // path==PERFORMER
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.ARTISTIC && path==PathInLife.CRAFTSMAN)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.GUILD_ARTISAN)};
end

rule "ACOLYTE" // interest==religious
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.RELIGIOUS)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.ACOLYTE)};
end

rule "interest_violent"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.VIOLENT)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.LAW_OBEYING)};
        modify($paths){add(PathInLife.LAW_BREAKING)};
end

rule "SOLIDER" // path=law_obeying
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.VIOLENT && path==PathInLife.LAW_OBEYING)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.SOLIDER)};
end

rule "CRIMINAL_2"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ORGANIZATION_MEMBER && interest==Interest.VIOLENT && path==PathInLife.LAW_BREAKING)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.CRIMINAL)};
end


// ONE PLACE
rule "wayoflife_one_place"
no-loop true
salience 101
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE)
        $interests: ArrayList();
    then
        System.out.println("ovddeeeee");
        modify($interests){add(Interest.SPIRITUAL)};
        modify($interests){add(Interest.ACADEMIC)};
end

rule "interest_spiritual"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE && interest==Interest.SPIRITUAL)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.TEMPLE_LIFE)};
        modify($paths){add(PathInLife.ISOLATED_LIFE)};
end

rule "interest_academic"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE && interest==Interest.ACADEMIC)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.DEDICATED)};
        modify($paths){add(PathInLife.HIGHBORN)};
end

rule "ACOLYTE_2"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE && interest==Interest.SPIRITUAL && path==PathInLife.TEMPLE_LIFE)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.ACOLYTE)};
end

rule "HERMIT_2"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE && interest==Interest.SPIRITUAL && path==PathInLife.ISOLATED_LIFE)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.HERMIT)};
end

rule "SAGE"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE && interest==Interest.ACADEMIC && path==PathInLife.DEDICATED)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.SAGE)};
end

rule "NOBLE"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.ONE_PLACE && interest==Interest.ACADEMIC && path==PathInLife.HIGHBORN)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.NOBLE)};
end


// WANDERING SPIRIT
rule "wayoflife_wanderer"
no-loop true
salience 101
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT)
        $interests: ArrayList();
    then
        modify($interests){add(Interest.FAMOUS)};
        modify($interests){add(Interest.SECLUDED)};
end

rule "interest_famous"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT && interest==Interest.FAMOUS)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.TALENTED_PERFORMER)};
        modify($paths){add(PathInLife.BRAVE_HERO)};
end

rule "ENTERTAINER_2"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT && interest==Interest.FAMOUS && path==PathInLife.TALENTED_PERFORMER)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.ENTERTAINER)};
end

rule "FOLK_HERO"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT && interest==Interest.FAMOUS && path==PathInLife.BRAVE_HERO)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.FOLK_HERO)};
end

rule "interest_secluded"
no-loop true
salience 75
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT && interest==Interest.SECLUDED)
        $paths: ArrayList();
    then
        modify($paths){clear()};
        modify($paths){add(PathInLife.THE_WILDS)};
        modify($paths){add(PathInLife.THE_SEA)};
end

rule "OUTLANDER"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT && interest==Interest.SECLUDED && path==PathInLife.THE_WILDS)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.OUTLANDER)};
end

rule "SAILOR"
no-loop true
salience 102
    when
        BackgroundParams(wayOfLife==WayOfLife.WANDERING_SPIRIT && interest==Interest.SECLUDED && path==PathInLife.THE_SEA)
        $cs: CharSheet()
    then
        modify($cs){setBackground(Background.SAILOR)};
end

//rule "worldly"
//no-loop true
//salience 25
//    when
//        $bp: BackgroundParams($wol: wayOfLife, $intr: interest, $path: path)
//        accumulate(
//            $wolSum: sum(WayOfLife())
//            $intrSum: sum(Interest())
//            $pathSum: sum(PathInLife())
//        )
//    then
//        modify($bp){$bp.worldly=($wolSum - $wol) * 0.6 + ($intrSum - $intr) * 0.1 + ($pathSum - $path) * 0.3}
//end
