package race;

import com.ftn.sbnz.model.CharSheet
import com.ftn.sbnz.model.Race;
import com.ftn.sbnz.model.RaceParams;
import com.ftn.sbnz.model.ColorPallette;
import com.ftn.sbnz.model.Skintone;
import com.ftn.sbnz.model.Disposition;
import com.ftn.sbnz.model.Feature;
import com.ftn.sbnz.model.Build;
import com.ftn.sbnz.model.Size;
import java.util.ArrayList;
import java.util.Arrays;
dialect  "mvel"

rule "short"
no-loop true
salience 100
    when
        RaceParams(size==Size.SHORT)
        $dispositions: ArrayList();
    then
        modify($dispositions){add(Disposition.MEEK)};
        modify($dispositions){add(Disposition.MISCHEVIOUS)};
        modify($dispositions){add(Disposition.HARDWORKING)};
        modify($dispositions){add(Disposition.CHILL)};
        modify($dispositions){add(Disposition.GENTLE)};
        modify($dispositions){add(Disposition.GRUFF)};
        modify($dispositions){add(Disposition.SNOBBY)};
end

rule "short_meek_mischevious"
no-loop true
salience 110
    when
        RaceParams(size==Size.SHORT, disposition == Disposition.MEEK || disposition == Disposition.MISCHEVIOUS)
        $palettes: ArrayList();
    then
        modify($palettes){add(ColorPallette.NATURAL)};
        modify($palettes){add(ColorPallette.UNNATURAL)};
end

rule "GOBLIN"
no-loop true
salience 111
    when
        RaceParams(size==Size.SHORT, disposition == Disposition.MEEK || disposition == Disposition.MISCHEVIOUS, pallette==ColorPallette.UNNATURAL)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.GOBLIN)};
end

rule "HALFLING_meek_mischevious"
no-loop true
salience 112
    when
        RaceParams(size==Size.SHORT, disposition == Disposition.MEEK || disposition == Disposition.MISCHEVIOUS, pallette==ColorPallette.NATURAL)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.HALFLING)};
end

rule "short_hardowrking"
no-loop true
salience 120
    when
        RaceParams(size==Size.SHORT, disposition == Disposition.HARDWORKING)
        $features: ArrayList()
    then
        modify($features){add(Feature.POINTY_EARS)};
        modify($features){add(Feature.NO_POINTY_EARS)};
end

rule "DWARF_hardowrking"
no-loop true
salience 121
    when
        $bp: RaceParams(size==Size.SHORT && disposition == Disposition.HARDWORKING, feature==Feature.POINTY_EARS)
        $cs: CharSheet()
//        $targetFeature: Feature.POINTY_EARS
    then
        modify($cs){setRace(Race.DWARF)};
end

rule "GNOME"
no-loop true
salience 122
    when
        RaceParams(size==Size.SHORT && disposition == Disposition.HARDWORKING, feature==Feature.NO_POINTY_EARS)
        $cs: CharSheet()
//        $targetFeature: Feature.POINTY_EARS
//        not(exists(Feature(this==Feature.POINTY_EARS) from $features))
    then
        modify($cs){setRace(Race.GNOME)};
end

rule "HALFLING_chill_gentle"
no-loop true
salience 130
    when
        RaceParams(size==Size.SHORT, disposition == Disposition.CHILL || disposition == Disposition.GENTLE)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.HALFLING)};
end

rule "DWARF_gruff_snobby"
no-loop true
salience 140
    when
        RaceParams(size==Size.SHORT, disposition == Disposition.GRUFF || disposition == Disposition.SNOBBY)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.DWARF)};
end

rule "medium"
no-loop true
salience 100
    when
        RaceParams(size==Size.MEDIUM)
        $palletes: ArrayList()
    then
        modify($palletes){add(ColorPallette.NATURAL)};
        modify($palletes){add(ColorPallette.UNNATURAL)};
end

rule "medium_unnatural"
no-loop true
salience 110
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.UNNATURAL)
        $builds: ArrayList();
    then
        modify($builds){add(Build.LEAN)};
        modify($builds){add(Build.STOCKY)};
        modify($builds){add(Build.BROAD)};
        modify($builds){add(Build.SLIGHT)};
end

rule "medium_unnatural_lean"
no-loop true
salience 111
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.UNNATURAL, build==Build.LEAN)
        $features: ArrayList()
    then
        modify($features){add(Feature.HORNS)};
        modify($features){add(Feature.NO_HORNS)};
end

rule "HALF-DROW"
no-loop true
salience 112
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.UNNATURAL, build==Build.LEAN, feature==Feature.NO_HORNS)
        $cs: CharSheet()
//        $targetFeature: Feature.HORNS
//        not(exists(Feature(this==Feature.HORNS) from $features))
    then
        modify($cs){setRace(Race.HALF_DROW)};
end

rule "TIEFLING"
no-loop true
salience 113
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.UNNATURAL, build==Build.LEAN, feature==Feature.HORNS)
        $cs: CharSheet()
//        $targetFeature: Feature.HORNS
    then
        modify($cs){setRace(Race.TIEFLING)};
end

rule "HALF-ORC"
no-loop true
salience 120
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.UNNATURAL, build == Build.STOCKY || build==Build.BROAD)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.HALF_ORC)};
end

rule "DROW"
no-loop true
salience 130
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.UNNATURAL, build==Build.SLIGHT)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.DROW)};
end


rule "medium_natural"
no-loop true
salience 140
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.NATURAL)
        $builds: ArrayList()
    then
        modify($builds){add(Build.LEAN)};
        modify($builds){add(Build.BROAD)};
        modify($builds){add(Build.SLIGHT)};

end

rule "medium_natural_lean"
no-loop true
salience 141
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.NATURAL, build == Build.LEAN)
        $features: ArrayList()
    then
        modify($features){add(Feature.POINTY_EARS)};
        modify($features){add(Feature.INNATE_MAGIC)};
end

rule "HALF-ELF"
no-loop true
salience 142
     when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.NATURAL, build==Build.LEAN, feature==Feature.POINTY_EARS)
        $cs: CharSheet()
//        $targetFeature: Feature.POINTY_EARS
    then
        modify($cs){setRace(Race.HALF_ELF)};
end

rule "HUMAN"
no-loop true
salience 143
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.NATURAL, build==Build.LEAN, feature==Feature.NO_POINTY_EARS)
        $cs: CharSheet()
//        $targetFeature: Feature.POINTY_EARS
//        not(exists(Feature(this==Feature.POINTY_EARS) from $features))
    then
        modify($cs){setRace(Race.HUMAN)};
end

rule "AASIMAR"
no-loop true
salience 150
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.NATURAL, build==Build.BROAD)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.AASIMAR)};
end

rule "ELF"
no-loop true
salience 151
    when
        RaceParams(size==Size.MEDIUM, pallette==ColorPallette.NATURAL, build==Build.SLIGHT)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.ELF)};
end


rule "tall"
no-loop true
salience 100
    when
        RaceParams(size==Size.TALL)
        $dispositions: ArrayList()
    then
        modify($dispositions){add(Disposition.HARDWORKING)};
        modify($dispositions){add(Disposition.CHILL)};
        modify($dispositions){add(Disposition.GENTLE)};
        modify($dispositions){add(Disposition.GRUFF)};
        modify($dispositions){add(Disposition.SNOBBY)};
end


rule "tall_gruff"
no-loop true
salience 310
    when
        RaceParams(size==Size.TALL, disposition == Disposition.GRUFF)
        $builds: ArrayList()
    then
        modify($builds){add(Build.STOCKY)};
        modify($builds){add(Build.LEAN)};
        modify($builds){add(Build.BROAD)};
end

rule "DRAGONBORN_gruff"
no-loop true
salience 311
    when
        $rp: RaceParams(size==Size.TALL, disposition == Disposition.GRUFF, build==Build.STOCKY || build==Build.LEAN)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.DRAGONBORN)};
        modify($rp){setPallette(ColorPallette.CHROMATIC_SCALES)};
end

rule "GOLIATH"
no-loop true
salience 312
    when
        $rp: RaceParams(size==Size.TALL, disposition == Disposition.GRUFF, build==Build.BROAD)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.GOLIATH)};
        modify($rp){setPallette(ColorPallette.UNNATURAL)};
        modify($rp){setSkintone(Skintone.GRAY)};
end

rule "FIRBOLG"
no-loop true
salience 320
    when
        RaceParams(size==Size.TALL, disposition == Disposition.GENTLE || disposition == Disposition.CHILL)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.FIRBOLG)};
end

rule "DRAGONBORN_snobby"
no-loop true
salience 330
    when
        $rp: RaceParams(size==Size.TALL, disposition == Disposition.SNOBBY)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.DRAGONBORN)};
        modify($rp){setPallette(ColorPallette.METALLIC_SCALES)};
        modify($rp){setFeature(Feature.SCALES)};
//        modify($rp){addFeature(Feature.TAIL)};

end

rule "DRAGONBORN_hardworking"
no-loop true
salience 331
    when
        $rp: RaceParams(size==Size.TALL, disposition == Disposition.HARDWORKING)
        $cs: CharSheet()
    then
        modify($cs){setRace(Race.DRAGONBORN)};
        modify($rp){setPallette(ColorPallette.CHROMATIC_SCALES)};
end

rule "natural_skintone"
no-loop true
salience 450
    when
        $cs: CharSheet(race==Race.HALFLING || race==Race.HUMAN || race==Race.DWARF ||
        race==Race.ELF || race==Race.HALF_ELF || race==Race.AASIMAR)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.LIGHT)};
        modify($skins){add(Skintone.MEDIUM)};
        modify($skins){add(Skintone.DARK)};
end

rule "underdark_skintone"
no-loop true
salience 450
    when
        $cs: CharSheet(race==Race.DROW || race==Race.DUEARGAR || race==Race.HALF_DROW)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.GRAY)};
        modify($skins){add(Skintone.INDIGO)};
end

rule "chromatic_scales_skintone"
no-loop true
salience 450
    when
        $rp: RaceParams(pallette==ColorPallette.CHROMATIC_SCALES)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.RED)};
        modify($skins){add(Skintone.GREEN)};
        modify($skins){add(Skintone.BLUE)};
        modify($skins){add(Skintone.WHITE)};
        modify($skins){add(Skintone.BLACK)};
end

rule "metallic_scales_skintone"
no-loop true
salience 450
    when
        $rp: RaceParams(pallette==ColorPallette.METALLIC_SCALES)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.GOLD)};
        modify($skins){add(Skintone.SILVER)};
        modify($skins){add(Skintone.BRASS)};
        modify($skins){add(Skintone.COPPER)};
        modify($skins){add(Skintone.BRONZE)};
end

rule "firbolg_skintone"
no-loop true
salience 450
    when
        $cs: CharSheet(race==Race.FIRBOLG)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.GREEN)};
        modify($skins){add(Skintone.BLUE)};
        modify($skins){add(Skintone.BROWN)};
        modify($skins){add(Skintone.GRAY)};
end

rule "tiefling_skintone"
no-loop true
salience 450
    when
        $cs: CharSheet(race==Race.TIEFLING)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.RED)};
        modify($skins){add(Skintone.PURPLE)};
end

rule "goblin_skintone"
no-loop true
salience 450
    when
        $cs: CharSheet(race==Race.GOBLIN || race==Race.HALF_ORC)
        $skins: ArrayList()
    then
        modify($skins){add(Skintone.YELLOW)};
        modify($skins){add(Skintone.GREEN)};
end

//rule "strangeness"
//no-loop true
//salience 70
//    when
//        accumulate(
//            $rp: RaceParams($features: features)
//            $fMin: min($features)
//            $sum: sum($features)
//            $count: count($count)
//        )
//    then
//        modify($rp){$rp.strangeIndex = ($sum-$min)/$count};
//
//end

